### ISSUE TITLE
No default sounds

### ISSUE THREAD

**Issue by voxdei** [tdimeco/QuickSound#11]
Would be better to have the app start with the collection of sounds present from your github repo. That would prevent us from downloading the whole project, storing the sounds some place in our computer, and importing them manually to have something to play with when we first start the app

**Comment by voxdei** [comment]
Another thing, if you ever move a sound already imported, then it does not work anymore.

You should consider copying the sounds inside the app

**Comment by tdimeco** [comment]
Yes I agree. For now, we plan to distribute the sounds package outside of the repo (in a separated optional zip you can download from the `releases` page). Because we want to avoid commiting/pushing/releasing a new app each time somebody add a new sound. With this solution, we only have to upload a new zip.

About copying sounds in the app bundle, it's not possible (the bundle is code signed). But we can think about copying files somewhere else (like Application Support/QuickSound/Sounds) maybe.
